# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503601c4132b3d85868f9b805aa142e3336e043f67abe5f9ec5c1d73e4ee5efc6533f88ad1ef69a3fb5ccd7b0121c7734f1294fca77d4ecc480dcf8540c51a6f

test:
  secret_key_base: 72d95c12fb1f8b0a84deeda7c5d5c4bcca7e9742aa1f9853f4fe96b46accf50b0f36598974e089e9c8c06c0a0d6abcb971f804ebe94cebb84fdc482778ff2d28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
